<a href="https://colab.research.google.com/github/GnokRacso/Degree-Year-2-Data-Science-/blob/master/Data%20Science/Practical/Numpy_Ans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
#[Numpy_Basic](https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html)

In [2]:
import numpy as np

np.arange((9)).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
x = np.random.random((10,10))
print(x)
print("Minimum Value:")
print(x.min())
print("Maximum Value:")
print(x.max())


[[5.28479070e-01 2.90750644e-01 6.49268765e-01 9.74550288e-01
  1.88412679e-01 6.34803774e-01 6.60972586e-01 5.11325979e-01
  5.65437013e-01 2.37864874e-02]
 [7.57182511e-01 9.71743146e-01 5.46127349e-01 5.11614356e-01
  9.12943750e-01 2.16319245e-01 6.43340585e-02 9.10422188e-01
  9.62687922e-01 1.68620753e-01]
 [3.82565002e-01 7.65057062e-01 3.11713030e-01 5.97165431e-01
  6.89031409e-01 1.05514540e-01 1.87553689e-01 6.88351382e-01
  1.94876711e-02 3.85795099e-01]
 [8.64130298e-01 8.71250991e-01 1.52821179e-01 8.21887940e-01
  7.81878665e-02 1.40309291e-01 2.96486805e-01 2.06128008e-01
  1.30902646e-01 3.15073423e-01]
 [3.71101678e-01 6.71038423e-01 6.29435152e-01 3.45110102e-01
  5.92745189e-01 2.51881031e-01 3.96943888e-02 7.14248099e-01
  5.01175129e-01 9.43476277e-01]
 [2.15245339e-01 4.89785377e-01 9.19557081e-01 3.43187718e-01
  8.05014030e-01 1.13426931e-01 9.39145649e-01 2.90045804e-01
  8.60999610e-01 1.20620292e-01]
 [5.74754589e-01 1.54241775e-01 9.75421160e-01 8.78673144e

In [5]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1 #x[start:final:step]=[1:0:0]
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [14]:
x = np.random.random(10)
print("Ori Array:")
print(x)
x[x.argmax()]=0
print("Max Value changed to 0:")
print(x)


Ori Array:
[0.74241893 0.65309914 0.85716067 0.95352941 0.15259017 0.93974749
 0.31845731 0.16218592 0.70083421 0.1260204 ]
Max Value changed to 0:
[0.74241893 0.65309914 0.85716067 0.         0.15259017 0.93974749
 0.31845731 0.16218592 0.70083421 0.1260204 ]


In [15]:
array = np.identity(4)
print(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
x = np.random.random((2,2))
print("2D Array:\n{}". format(x))

2D Array:
[[0.60861246 0.60559747]
 [0.45149241 0.9670344 ]]


In [27]:
x = np.random.normal(0,1,(4,4,4))
print("3D-Array:\n")
print(x)

#[Resources](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.normal.html)

3D-Array:

[[[-1.72150358  0.66517524 -0.9902778  -2.543668  ]
  [ 0.56091127 -0.43459236 -0.09609617  1.16134002]
  [-0.79742563  0.14158771  0.76655957  0.8428354 ]
  [ 1.118115   -0.46426254  0.05088608  1.25784844]]

 [[-0.25543279  2.52117898 -0.15463217  0.26212883]
  [ 0.91461437 -0.72026007 -0.16361962  0.66860406]
  [-0.39165803  0.30667769 -1.00451791 -0.20545751]
  [-0.6661125   1.1008023   0.51615811 -0.49769897]]

 [[-0.73377018 -0.44414184  0.08995508 -0.45794156]
  [-2.0616186   1.12145964 -1.25986663  0.10376878]
  [-0.76952984  1.42874921  1.37524826 -0.57922249]
  [ 0.94643235 -1.21324691  1.46243181 -1.47969592]]

 [[ 0.03474686 -0.50947538 -0.88810027  0.65501198]
  [ 1.66253679  0.04198602  0.31579888 -0.72250394]
  [-0.49925057  0.66045068 -0.25709767 -1.4001375 ]
  [-0.40799367 -0.2184026   0.03512489  0.01399708]]]


In [33]:
x = np.arange(0,1,0.1)
print(x)
print("\n or \n")
y = np.linspace(0,1, num=11)
print(y)

#[Resource](https://thispointer.com/numpy-arange-create-a-numpy-array-of-evenly-spaced-numbers-in-python/)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

 or 

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [36]:
x = np.arange(0,10)
print(x)
print("\nReversed Array")
x = x[::-1]
print(x)

[0 1 2 3 4 5 6 7 8 9]

Reversed Array
[9 8 7 6 5 4 3 2 1 0]
