<a href="https://colab.research.google.com/github/GnokRacso/Degree-Year-2-Data-Science-/blob/master/Data%20Science/Practical/Practical3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

np.arange((9)).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
x = np.random.random((10,10))
print(x)
print("Minimum Value:")
print(x.min())
print("Maximum Value:")
print(x.max())


[[0.04081794 0.39877921 0.24882425 0.33272247 0.71333943 0.68195313
  0.44737424 0.58112602 0.91817843 0.72503805]
 [0.52450102 0.03940846 0.10982878 0.52503629 0.54645116 0.98432679
  0.70059954 0.84356272 0.25520347 0.33442406]
 [0.24413379 0.89559867 0.13857121 0.65980265 0.01159158 0.5092085
  0.24494369 0.45942364 0.15088005 0.80795618]
 [0.03415192 0.53868222 0.51260069 0.70368735 0.73833911 0.52284792
  0.25577794 0.49493683 0.52309889 0.01537651]
 [0.12336212 0.09746387 0.5069229  0.34579407 0.24666854 0.99190257
  0.15986116 0.28765616 0.57533701 0.44295878]
 [0.86085144 0.43058552 0.13722677 0.30447796 0.96458755 0.74525046
  0.81036044 0.77608088 0.23451551 0.13487108]
 [0.40553124 0.61832464 0.53575132 0.39780874 0.73040362 0.61032522
  0.55958357 0.67529001 0.72033011 0.5232897 ]
 [0.89975934 0.33135748 0.18978832 0.69146057 0.81908019 0.85285393
  0.98755941 0.46169737 0.95992076 0.57053   ]
 [0.90873987 0.4909412  0.39939357 0.30079022 0.75703446 0.70000169
  0.01606572 

In [23]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
